{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lampac.fullname" . }}-cache
  labels:
    {{- include "lampac.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  {{- if .Values.persistence.cache.storageClass }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
