---
name: Test - Build all projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: read
  packages: read
  id-token: write

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION || '10.0.x' }}

      - name: Restore
        run: dotnet restore --verbosity minimal NextGen.slnx

      - name: Build
        run: dotnet build NextGen.slnx --configuration Release --verbosity minimal
